# Generated by Django 4.0.1 on 2022-07-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
