# Generated by Django 4.0.1 on 2022-08-29 04:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapp', '0001_initial'),
        ('cartapp', '0005_wishlisteditems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistedItems',
            new_name='WishlistedItem',
        ),
    ]
