# Generated by Django 4.0.1 on 2022-08-29 04:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartapp', '0006_rename_wishlisteditems_wishlisteditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistedItem',
            new_name='WishlistItem',
        ),
    ]
